version: '3.1'

services:

  product_db:
   container_name: postgres
   restart: always
   image: postgres:latest
   volumes:
     - C:/DockerVolumes/postgresql-data:/var/lib/postgresql/data
   ports:
     - "5433:5432"